#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EHBO.Resource", IsApplication=true)]

namespace EHBO
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int musicList = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ic_launcher_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int activity_horizontal_margin = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int activity_vertical_margin = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0016
			public const int SnoozeButton = 2131427350;
			
			// aapt resource value: 0x7f0b0015
			public const int StopAlarmButton = 2131427349;
			
			// aapt resource value: 0x7f0b000c
			public const int ToggleKoffie = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int ToggleLicht = 2131427341;
			
			// aapt resource value: 0x7f0b0018
			public const int abort = 2131427352;
			
			// aapt resource value: 0x7f0b0010
			public const int autoConnect = 2131427344;
			
			// aapt resource value: 0x7f0b000e
			public const int checkBox1 = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int checkBox2 = 2131427343;
			
			// aapt resource value: 0x7f0b0017
			public const int exit = 2131427351;
			
			// aapt resource value: 0x7f0b000a
			public const int goMusic = 2131427338;
			
			// aapt resource value: 0x7f0b0014
			public const int imageView1 = 2131427348;
			
			// aapt resource value: 0x7f0b0013
			public const int musicButton = 2131427347;
			
			// aapt resource value: 0x7f0b0002
			public const int oneshotAlarm = 2131427330;
			
			// aapt resource value: 0x7f0b000b
			public const int relativeLayout1 = 2131427339;
			
			// aapt resource value: 0x7f0b0012
			public const int selectMusic = 2131427346;
			
			// aapt resource value: 0x7f0b0006
			public const int set = 2131427334;
			
			// aapt resource value: 0x7f0b0009
			public const int snooze = 2131427337;
			
			// aapt resource value: 0x7f0b0003
			public const int stoprepeatingAlarm = 2131427331;
			
			// aapt resource value: 0x7f0b0000
			public const int textView = 2131427328;
			
			// aapt resource value: 0x7f0b0004
			public const int textView1 = 2131427332;
			
			// aapt resource value: 0x7f0b0007
			public const int textView2 = 2131427335;
			
			// aapt resource value: 0x7f0b0011
			public const int textViewServerConnect = 2131427345;
			
			// aapt resource value: 0x7f0b0005
			public const int tijd = 2131427333;
			
			// aapt resource value: 0x7f0b0001
			public const int timePicker = 2131427329;
			
			// aapt resource value: 0x7f0b0008
			public const int txtCountdown = 2131427336;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Alarmcontroller_Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int musicLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Wakescreen_Layout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int menu = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher_foreground = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher_round = 2130837506;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Discussion = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Freaks = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Rattlesnake = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Sparkle = 2130968579;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070017
			public const int abort = 2131165207;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int application_name = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int arduino_server_connect = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int arduino_server_text = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int buttonAuto = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int button_connect_text = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int button_pin_state_text = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int change_pin_state_value = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int debug_text = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int debug_value = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int exit = 2131165206;
			
			// aapt resource value: 0x7f070009
			public const int ip_address_text = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int ip_address_value = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int ip_port_text = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int ip_port_value = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int musicButton = 2131165203;
			
			// aapt resource value: 0x7f070004
			public const int musicSelector = 2131165188;
			
			// aapt resource value: 0x7f070019
			public const int one_shot_scheduled = 2131165209;
			
			// aapt resource value: 0x7f07000f
			public const int pin_state_text = 2131165199;
			
			// aapt resource value: 0x7f07001a
			public const int repeating_scheduled = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int repeating_unscheduled = 2131165211;
			
			// aapt resource value: 0x7f070011
			public const int sensor_text = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int sensor_value = 2131165202;
			
			// aapt resource value: 0x7f070018
			public const int setttime = 2131165208;
			
			// aapt resource value: 0x7f070003
			public const int text = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int timer_state_text = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int timer_state_value = 2131165190;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
